### ISSUE TITLE
VL6180x...

### ISSUE THREAD

**Issue by ShardulKK** [pololu/vl6180x-arduino#1]
Hello.....
I used the library given for VL6180x breakout board of Pololu, and it works fine with my Aruino Uno.
The only issue is, the sampling rate of 10Hz is not enough for my application.
In all the reading appear on the serial monitor screen after half second approx.

I require speed of at least 100Hz or more, and readings  must appear after 10ms.

I am not exactly sure how to achieve this, and which parameters must be changed or controlled to get this much speed smoothly,
Could I get some help please?

Also, what is the meaning of 'convergence time'?

**Comment by kevin-pololu** [comment]
Hello,
I recommend reading sections 2.4.4 and 2.5 in the VL6180X datasheet for information about what determines the sampling rate of the sensor. I was able to get range readings at about 100 Hz by reducing SYSRANGE__MAX_CONVERGENCE_TIME to 5 and READOUT__AVERAGING_SAMPLE_PERIOD to 24 and using a 10 ms range intermeasurement period. Note that reducing these values will probably decrease the performance of the sensor (it will probably be more noisy and less sensitive), and you might want to try tweaking the values yourself for better results. It is probably not practical to get ambient light measurements at 100 Hz, although I haven't tried.

I don't think "convergence time" is explained in detail, but my understanding is that it is the time the sensor takes to settle on (calculate) a measurement. If it takes longer than the max limit, the ranging will be aborted and the sensor will report 255.

I don't know why you are seeing a half second delay before getting readings. If you want to troubleshoot this further with us (or want more help with the other settings), please contact us through our regular support channels: https://www.pololu.com/contact (The GitHub issues are intended to track development of and issues with the library code itself.)
