### ISSUE TITLE
Example on Arduino Nano RP2040 Connect

### ISSUE THREAD

**Issue by ajsb85** [pololu/vl6180x-arduino#13]
I just want to report that the examples does not works with Arduino Nano RP2040 Connect.
Tested with Adafruit and Sparkfun breakout boards

![image](https://user-images.githubusercontent.com/663460/120517219-83654c80-c3d0-11eb-81d2-ca798fd693b9.png)
![image](https://user-images.githubusercontent.com/663460/120517381-b0196400-c3d0-11eb-934c-73eff9cc1e76.png)

References:

https://www.sparkfun.com/products/12785
https://www.adafruit.com/product/3316
https://store.arduino.cc/nano-rp2040-connect

**Comment by ryantm** [comment]
Thanks for the report. What problem are you seeing?

**Comment by kevin-pololu** [comment]
I just released version 1.3.1, which should fix some compilation errors with the Arduino mbed core (including with the Nano RP2040 Connect). Please let us know if that resolves the problem you had.

In the future, when you submit an issue, it would be helpful if you could provide details on the problem you are seeing and how to reproduce it.

Kevin
