### ISSUE TITLE
"Timeout" not triggered when module disconnected

### ISSUE THREAD

**Issue by celestinmetral** [pololu/vl6180x-arduino#14]
Hello,

I've made some tests with your module and RangeSensorDriver example of your library, specifically around the "timeout" feature. I've found out that when I disconnect your module from the I²C bus, the "timeout" does not trigger. It triggers only when computation takes too much times, but I think it could be great if it triggered when module is disconnected.

After digging inside your library, I think I've found the culprit, in VL6180X.cpp, line 346:
`while ((readReg(RESULT__INTERRUPT_STATUS_GPIO) & 0x04) == 0)`

- while computation is ongoing, the register is set to 0x00 (program looping inside `while`)
- when computation is finished, the register is set to 0x04 ([source (page 5, bullet 10)](https://www.st.com/resource/en/design_tip/dt0037-vl6180x-range-and-ambient-light-sensor-quick-setup-guide-stmicroelectronics.pdf)) (program exiting `while` loop)
- but when module is disconnected, the register is read as 0xFF (255)!

As you can see in the code line above, the condition evaluates as false when the module is disconnected, so the program does not even enter the `while` loop, range is read and timeout does not triggers.

My suggestion is to edit the line as :
`while ((readReg(RESULT__INTERRUPT_STATUS_GPIO) != 0x04)`

Do you find this a good idea or do I forgot a use case ? If you think we could edit the library, could I make a pull request (I've never made one !) ?

Thanks, Célestin

**Comment by celestinmetral** [comment]
Hello again,
I've made a pull request (my first ! so please check if everything is alright) to fix this. I don't know if it's a bugfix or a new feature, I'll let you decide.
#15 
Thanks

**Comment by kevin-pololu** [comment]
Closing this since I merged #15. Thanks!
