### ISSUE TITLE
Can't getting 0 value from Range sensor

### ISSUE THREAD

**Issue by suathh** [pololu/vl6180x-arduino#3]
Hello my sensor is working just fine between 255-10mm values but when i put something closer than 10mm sensor doesn't show it and values are not stable it can say for same object in same spot 22mm 23mm or 20mm. What sould I do ? Thanks

**Comment by ryantm** [comment]
Hello, suath.

You are probably running into the minimum range issue that all sensors that sense reflected light have: if the light cannot get back to the sensor, it cannot be sensed. Recessing your sensor so that the close range is not occupied is typically how people fix this problem.

Ryan
