### ISSUE TITLE
Water surface level measure ? 

### ISSUE THREAD

**Issue by jszetoo** [pololu/vl6180x-arduino#5]
Would it work on, Water surface level measure ?   Any advise, would be very helpful.  Thanks in Advance

**Comment by ryantm** [comment]
Hi, @jszetoo.

Sorry for the very late reply. This issue tracker is for issues with the library or example code. If you have technical questions about the product, please post on our forum https://forum.pololu.com/.

Sincerely,
Ryan Mulligan
