### ISSUE TITLE
Vl 6180

### ISSUE THREAD

**Issue by NahuelCarro** [pololu/vl6180x-arduino#7]
Hi, I wanted to see if you could help me with the VL6180x sensor, I tried in many ways but I always get stuck in the 0x18 register, it never gets 0x4. Thank you
y.zip

**Comment by kevin-pololu** [comment]
Please post on the [Pololu forum](https://forum.pololu.com/), since that is a more appropriate place for troubleshooting. (The GitHub issues are intended to track development of and problems with the library code itself.)
