### ISSUE TITLE
How to calculate time with Time of Flight sensor

### ISSUE THREAD

**Issue by Gbouna** [pololu/vl6180x-arduino#8]
Thank you for your tutorial, they were really helpful to get me started. 
However i have quite a simple question but i do not know how to get my mind around it. 

And according to the datasheet, Effective max convergence time depends on the actual convergence time plus readout averaging sample period setting. Please i want to know how to calculate the convergence time. 

This is simply because i want to be able to calculate speed. Since the sensor reads distance, if i know the time, then i can calculate speed. 
Thank you

**Comment by DavidEGrayson** [comment]
If you're still looking for help with this, you can learn about the timing of the VL6180X distance measurements by reading the "Range timing" section of the datasheet.  You might also want to read my comments in https://github.com/pololu/vl6180x-arduino/issues/9 .

However, VL6180X readings do not always take the same amount of time.  So if you are trying to calculate the speed of an object, it is probably better to just read the current time using the Arduino `millis()` or `micros()` functions.  Then you can divide a change in distance by a change in the time to get a speed.

We use GitHub issues to keep track of features and bugs in the library, not as a general discussion board.  If you have more questions like this one, please post on our forum:

https://forum.pololu.com/
